version: '3.0'

services:
  cocus-backend-application:
    build: .
    container_name: cocus-backend-application
    volumes:
      - ./application:/usr/src/app/cocus-backend-application
    environment:
      PORT: 3333
      HEADER_ACCEPT: application/json
      GIT_REPOSITORY_API_URL: https://api.github.com
    ports:
    - 3333:3333
    networks:
      localnet:
        ipv4_address: 172.52.0.5

  cocus-backend-webserver:
    build: ./webserver
    container_name: cocus-backend-webserver
    networks:
      localnet:
        ipv4_address: 172.52.0.7

networks:
  localnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.52.0.0/16
